// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/ZTE/Knitter/knitter-monitor/services (interfaces: PodServiceInterface)

package mockservices

import (
	gomock "github.com/golang/mock/gomock"
	v1 "k8s.io/api/core/v1"
	infra "github.com/ZTE/Knitter/knitter-monitor/infra"
	services "github.com/ZTE/Knitter/knitter-monitor/services"
	agt_mgr "github.com/ZTE/Knitter/pkg/inter-cmpt/agt-mgr"
)

// Mock of PodServiceInterface interface
type MockPodServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *_MockPodServiceInterfaceRecorder
}

// Recorder for MockPodServiceInterface (not exported)
type _MockPodServiceInterfaceRecorder struct {
	mock *MockPodServiceInterface
}

func NewMockPodServiceInterface(ctrl *gomock.Controller) *MockPodServiceInterface {
	mock := &MockPodServiceInterface{ctrl: ctrl}
	mock.recorder = &_MockPodServiceInterfaceRecorder{mock}
	return mock
}

func (_m *MockPodServiceInterface) EXPECT() *_MockPodServiceInterfaceRecorder {
	return _m.recorder
}

func (_m *MockPodServiceInterface) DeletePodAndPorts(_param0 string, _param1 string) error {
	ret := _m.ctrl.Call(_m, "DeletePodAndPorts", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockPodServiceInterfaceRecorder) DeletePodAndPorts(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeletePodAndPorts", arg0, arg1)
}

func (_m *MockPodServiceInterface) Get(_param0 string, _param1 string) (*services.Pod, error) {
	ret := _m.ctrl.Call(_m, "Get", _param0, _param1)
	ret0, _ := ret[0].(*services.Pod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockPodServiceInterfaceRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Get", arg0, arg1)
}

func (_m *MockPodServiceInterface) NewPodFromK8sPod(_param0 *v1.Pod) (*services.Pod, error) {
	ret := _m.ctrl.Call(_m, "NewPodFromK8sPod", _param0)
	ret0, _ := ret[0].(*services.Pod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockPodServiceInterfaceRecorder) NewPodFromK8sPod(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "NewPodFromK8sPod", arg0)
}

func (_m *MockPodServiceInterface) PatchReportPod(_param0 string, _param1 string, _param2 *agt_mgr.AgentPodReq) error {
	ret := _m.ctrl.Call(_m, "PatchReportPod", _param0, _param1, _param2)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockPodServiceInterfaceRecorder) PatchReportPod(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "PatchReportPod", arg0, arg1, arg2)
}

func (_m *MockPodServiceInterface) ReportDeletePod(_param0 string, _param1 string) error {
	ret := _m.ctrl.Call(_m, "ReportDeletePod", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockPodServiceInterfaceRecorder) ReportDeletePod(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ReportDeletePod", arg0, arg1)
}

func (_m *MockPodServiceInterface) ReportPod(_param0 *infra.ReportPod) error {
	ret := _m.ctrl.Call(_m, "ReportPod", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockPodServiceInterfaceRecorder) ReportPod(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ReportPod", arg0)
}

func (_m *MockPodServiceInterface) Save(_param0 *services.Pod) error {
	ret := _m.ctrl.Call(_m, "Save", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockPodServiceInterfaceRecorder) Save(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Save", arg0)
}
